trigger:
- master
parameters:
- name: artifacts
  type: object
  default:
  - safeName: a
  - safeName: b
  - safeName: c
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-18.04
    steps:
    - checkout: none
    - script: echo "Building..."
  - job: Analyze
    pool:
      vmImage: ubuntu-18.04
    steps:
    - checkout: none
    - script: echo "Analyzing..."
  - job: Test
    strategy:
      maxParallel: 2
      matrix:
        Ubuntu_18.04:
          vmImage: ubuntu-18.04
        Ubuntu_16.04:
          vmImage: ubuntu-16.04
    pool:
      vmImage: $(vmImage)
    steps:
    - checkout: none
    - script: echo "Testing..."
- stage: Signing
  dependsOn: Build
  jobs:
  - job: Sign
    pool:
      vmImage: ubuntu-18.04
    steps:
    - checkout: none
    - script: echo "Signing..."
- ${{ each artifact in parameters.artifacts }}:
  - stage: Release_${{ artifact.safeName }}
    displayName: 'Release: ${{ artifact.safeName }}'
    dependsOn: Signing
    jobs:
    - deployment: TagRepository
      displayName: Create release tag
      continueOnError: true
      environment: github
      pool:
        vmImage: ubuntu-18.04
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - script: |
                if [ '${{ artifact.safeName }}' == 'c' ]; then
                  exit 1
                fi
                echo "Tagging ${{ artifact.safeName }}"
    # BUGBUG: continueOnError from skipped deployment job does not continue to a subsequent job in the same stage.
    - job: Check
      condition: always()
      pool:
        vmImage: ubuntu-18.04
      steps:
      - checkout: none
      - script: echo "$(variables['Agent.JobStatus'])"
- stage: Integration
  dependsOn: Signing
  jobs:
  - job: PublishPackages
    pool:
      vmImage: ubuntu-18.04
    steps:
    - checkout: none
    - script: echo "Publishing packages to daily feed"